apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
spec:
  containers:
  - name: {{ .Values.pod.name }}
    image: {{ .Values.pod.image.repository }}
    imagePullPolicy: {{ .Values.pod.image.pullPolicy }}
    command: {{ .Values.pod.command }}
