apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ops
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.7
    helm:
      releaseName: grafana
      values: |
        service:
          type: LoadBalancer
          annotations:
            "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
        persistence:
          enabled: true
  destination:
    name: in-cluster
    namespace: kabirg
  syncPolicy:
    syncOptions:
     - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
