apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testpod-worker
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kaguptas/iac-testing
    targetRevision: HEAD
    path: app0
  destination:
    name: https://5ED34734319348DF09789C3B28D017F3.gr7.us-west-2.eks.amazonaws.com
    namespace: kabirg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
