apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testpod0
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kaguptas/iac-testing
    targetRevision: HEAD
    path: app0
  destination:
    name: dev-kgupta-worker
    namespace: kabirg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
