apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testpod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kaguptas/iac-testing.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
