apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ops
  source:
    repoURL: https://github.com/kaguptas/iac-testing
    targetRevision: HEAD
    path: apps
    # directory:
    #   include: '{apps/app/appsource/application.yaml,apps/apptwo/apptwosource/application.yaml,apps/appthree/appthreesource/application.yaml}'
    #   recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kabirg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
