apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ops
  sources:
  - chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
  - repoURL: https://github.com/kaguptas/iac-testing
    path: ./
    targetRevision: HEAD
    directory:
      include: '{stack/overlays/dev/application.yaml}'
      recurse: true
  - repoURL: https://github.com/kaguptas/iac-testing-dev
    path: ./
    targetRevision: HEAD
    directory:
      include: '{env/dev/application.yaml}'
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kabirg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
