apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testpod-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kaguptas/iac-testing
    targetRevision: HEAD
    path: appthree/appthreesource
  destination:
    server: https://kubernetes.default.svc
    namespace: kabirg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
